### PR TITLE
Fixed NAN Statement issue

### PR DESCRIPTION
**Pull request by Ataurr**

### CODE REVIEW

**Comment by MoradHamdy** [comment]
@Ataurr

Do you know how to use this fix without waiting the approve of pull request?

**Comment by Ataurr** [comment]
@MoradHamdy https://github.com/dtbaker/dashboard-plus#development-howto

**Comment by MoradHamdy** [comment]
@Ataurr 

I found some issue with the tax amount. It shows the same value of net earns. Also the number of taxed item is not correct.

img-3

**Comment by Ataurr** [comment]
@MoradHamdy can you please try one more time.

**Comment by MoradHamdy** [comment]
@Ataurr I will check now.

**Comment by MoradHamdy** [comment]
@Ataurr Thanks a lot. It's now fixed! :)

img-6

**Comment by themechampion** [comment]
Hello,

I removed it from chrome and trying to reinstall… It gives error while going to install it from the Webstore: 
https://prnt.sc/o6reid

Please suggest

**Comment by dtbaker** [comment]
Thanks all!! I'll push this up to chrome web store now :)

**Comment by dtbaker** [comment]
Fixed in https://github.com/dtbaker/dashboard-plus/commit/864c3666a3c193a52ee6953e4bff24acaa54f8c4

**Comment by themechampion** [comment]
Hello @dtbaker 

Unfortunately, it doesn't work https://chrome.google.com/webstore/detail/dashboard-plus-for-envato/gcbcdaghonmljaplbpbbimmmfhmhcheh

Please have a look.

Thank you

**Pull request closed without merging**
